version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/sample_mflix
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3001
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sample_mflix
    restart: unless-stopped

volumes:
  mongodb_data:
