services:
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/Users/d/github/whatchamacallit/.mdb/
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mongo-data:

# To import the mflix sample dataset after the container is running:
# 1. Download the mflix dataset
# 2. Unzip and use:
#    mongoimport --uri "mongodb://root:password@localhost:27017/mflix?authSource=admin" --collection movies --file movies.json --jsonArray
# (You can run this from your host or inside the container) 