services:
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/Users/d/github/whatchamacallit/.mdb/
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mongo-data:
#    mongoimport --uri "mongodb://localhost:27017/sample_mflix" --collection embedded_movies --file ../sample_mflix.embedded_movies.json --jsonArray
